# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Zettersten.Shnapp
PackageVersion: 1.0.0
InstallerType: zip
NestedInstallerType: portable
ArchiveBinariesDependOnPath: true
MinimumOSVersion: 10.0.22000.0
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Zettersten/shhnap/releases/download/v1.0.0/Shnapp-win-x64.zip
    InstallerSha256: fddf0cd3699e811e5e6e6b550cd1208952298b42d6b482ffa37fcdb9f6e67af2
    NestedInstallerFiles:
      - RelativeFilePath: Shnapp.exe
        PortableCommandAlias: shnapp
  - Architecture: arm64
    InstallerUrl: https://github.com/Zettersten/shhnap/releases/download/v1.0.0/Shnapp-win-arm64.zip
    InstallerSha256: 161e54a384b3255a258ee48296057780424088ba62d0bcb81a2d1b7714d28f15
    NestedInstallerFiles:
      - RelativeFilePath: Shnapp.exe
        PortableCommandAlias: shnapp
ManifestType: installer
ManifestVersion: 1.10.0
