# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
PackageIdentifier: Zettersten.Shnapp
PackageVersion: 1.0.4
PackageLocale: en-US
Publisher: Erik Zettersten
PublisherUrl: https://zettersten.com
PublisherSupportUrl: https://github.com/Zettersten/shhnap/issues
Author: Erik Zettersten
PackageName: Shnapp
PackageUrl: https://shhnap.com
License: MIT
LicenseUrl: https://github.com/Zettersten/shhnap/blob/main/LICENSE
ShortDescription: Screenshot capture and annotation for Windows.
Tags:
  - screenshot
  - capture
  - annotation
ManifestType: defaultLocale
ManifestVersion: 1.10.0
